#!/usr/bin/env python3
import sys
import csv
class Args(object):
	def __init__(self):
		self.args = sys.argv[1:]
	def index(self,index):
		try:
			position = argv.find(index) + 1
			return argv[position + 1]
		except ValueError:
			print("invalid input")

class Config(object):
	def __init__(self):
		self.config = self._read_config()
	def _read_config(self):
		try:
			config = {}
			file1 = open(Config.index('-c'))
			l = file1.readlines()
			i = 0
			while i < len(l):
				ll[i] = l[i].split('=')
				ll[i][0].strip(' ')
				ll[i][1].strip(' ')
				config[ll[i][0]] = ll[i][1]
				i = i + 1
			file1.close()
			return config
		except TypeError:
			print("invalid input")
class UserData(object):
	try:
		def __init__(self):
			self.userdata = self._read_users_data()
		def _read_users_data(self):
			userdata = []
			file1 = open(UserData.index('-d'))
			i = 0
			ID = []
			Salary = []
			l = file1.readlines()
			while i < len(l):
				ll[i] = l[i].split(',')
				ID = ll[i][0]
				salary = ll[i][1]
				userdata.append((ID,salary))
				i = i + 1
			file1.close()
			return userdata
	except ValueError:
		print("invalid value")
class IncomeTexCalculator(object):
	def calc_for_all_userdata(self):
		i = 0
		l = userdata
		bfinal = []
		#use b to save final
		while i < len(l):
		# calculate the amount need to pay shebao
			Total = int(l[i][1])
			shebao = 0
			if Total < 2193:
				shebao = 2193 * 0.165
			elif Total > 16446:
				shebao = 16446 * 0.165
			else:
				shebao = Total * 0.165
			try:
				i = 1
				wrate = 0.165
			#	while j < len(a):
			#tax1: amount need to pay tax
				Total = Total - shebao
				if Total < 0:
					Total = 0
				tax1 = Total - 3500
				if tax1 <= 1500:
					rate = 0.03
					number = 0
				elif tax1 > 1500 and tax1 <= 4500:
					rate = 0.1
					number = 105
				elif tax1 > 4500 and tax1 <= 9000:
					rate = 0.2
					number = 555
				elif tax1 > 9000 and tax1 <=35000:
					rate = 0.25
					number = 1005
				elif tax1 > 35000 and tax1 <= 55000:
					rate = 0.3
					number = 2755
				elif tax1 > 55000 and tax1 <=80000:
					rate = 0.35
					number = 5505
				elif tax1 > 80000:
					rate = 0.45
					number = 13505
				if tax1 < 0:
					tax = 0
				else:
					tax = tax1 * rate - number
				ftotal = Total - tax
				bfinal.append(ftotal)
				i = i + 1
				while k < len(l):
					d = l[k][0]
					c = bfinal[k]
					print("{}:{:6.2f}".format(d,c))
					k = k + 1
			except ValueError:
				print("Parameter Error")
	def export(self,default = 'csv'):
		result = self/calc_for_all_userdata()
		with open(IncomeTaxCalculator.index('-o')) as f:
			writer = csv.writer(f)
			writer.writerows(result)

if __name__ == '__main__':
	print('test')
